[package]
name = "euc"
version = "0.5.2"
description = "A software rendering crate that lets you write shaders with Rust"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>", "Martin Sandfuchs <martin@cluginbuehl.ch>"]
license = "Apache-2.0 AND MIT"
repository = "https://github.com/zesterer/euc"
readme = "README.md"
edition = "2018"
keywords = ["renderer", "3D", "graphics", "raster"]
exclude = [
	"/misc",
	"/misc/*",
]

[dependencies]
num-traits = { version = "0.2", default-features = false, optional = true }
vek = { version = "0.12", default-features = false, features = [] }

[features]
default = ["std", "simd"]
std = ["vek/std"]
libm = ["vek/libm", "num-traits"]
nightly = []
simd = ["vek/repr_simd"]

[dev-dependencies]
mini_gl_fb = "0.7.0"
tobj = "2.0.2"
criterion = "0.3.3"
image = "0.23.12"
vek = "0.12.1"

[lib]
bench = false

[[bench]]
name = "teapot"
harness = false

[profile.dev]
# Optimize by default so we don't need to remember to always pass in --release
opt-level = 3
